name: CI/CD to Hugging Face Spaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate  # Corrected for cross-platform usage
        pip install -r requirements.txt

    - name: Set Hugging Face API token
      run: echo "HF_TOKEN=${{ secrets.HF_Token }}" >> $GITHUB_ENV

    - name: Deploy to Hugging Face Spaces
      run: |
        pip install huggingface_hub
        # Login using the Hugging Face API token
        huggingface-cli login --token ${{ secrets.HF_Token }}
        # Add Hugging Face remote repository (optional if remote already exists)
        git remote add huggingface https://huggingface.co/spaces/rabailanees/hugging-face-demo.git
        # Configure Git to use the token for authentication
        git config --global credential.helper store
        echo "https://${{ secrets.HF_Token }}:x-oauth-basic" > ~/.git-credentials
        # Push to Hugging Face repository
        git push huggingface main
