name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the main branch
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Step 2: Set up Python environment (optional if required by your project)
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # or 'venv\Scripts\activate' for Windows
          pip install -r requirements.txt

      # Step 4: Set the Hugging Face token and add remote repository
      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/rabail03/hugging-face-demo.git
          git config --global credential.helper store

      # Step 5: Push to Hugging Face Spaces
      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Save the Hugging Face token to git credentials helper
          echo "https://huggingface.co:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
          git config --global credential.helper store
          git push --force https://huggingface.co/spaces/rabail03/hugging-face-demo.git main
