name: CI/CD to Hugging Face Spaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate  # Corrected for cross-platform usage
        pip install -r requirements.txt

    - name: Set Hugging Face API token
      run: echo "HF_TOKEN=${{ secrets.HF_Token }}" >> $GITHUB_ENV

    - name: Deploy to Hugging Face Spaces
      run: |
        pip install huggingface_hub
        huggingface-cli login --token ${{ secrets.HF_Token }}
        # Ensure that you are authenticated for both huggingface-cli and git
        git remote add huggingface https://huggingface.co/spaces/rabailanees/hugging-face-demo.git
        git push https://huggingface.co/spaces/rabailanees/hugging-face-demo.git main
